# Sourced by the run scripts. DART_DEFINES holds a --dart-define for each
# allowed setting: from the environment when it's set there (scripts/deploy.sh
# sets the cloud IDs), otherwise from the repo's .env (see .env.example).
#
# Only the names below are passed: anything given to Flutter is compiled
# into the app (readable in the web bundle), so secrets in .env, such as
# the client secret, must never be listed here. These are all public
# identifiers.
_allowed=(GOOGLE_WEB_CLIENT_ID GOOGLE_IOS_CLIENT_ID AWS_REGION COGNITO_IDENTITY_POOL_ID USER_DATA_BUCKET FEEDBACK_TABLE IOT_ENDPOINT PRESENCE_STAGE)
_env="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"
DART_DEFINES=()
[[ -f "$_env" ]] || echo "note: no .env; Google sign-in will say it isn't set up (see .env.example)" >&2
for _name in "${_allowed[@]}"; do
  _value="${!_name:-}"
  if [[ -z "$_value" && -f "$_env" ]]; then
    _value="$(sed -n "s/^${_name}=//p" "$_env" | tail -1)"
  fi
  [[ -n "$_value" ]] && DART_DEFINES+=(--dart-define="${_name}=${_value}")
done

# iOS reads the reversed iOS client ID (its sign-in URL scheme) from a
# git-ignored xcconfig, so the ID isn't committed.
_ios="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/presence_app/ios/Flutter/Private.xcconfig"
_value="${GOOGLE_IOS_CLIENT_ID:-}"
[[ -z "$_value" && -f "$_env" ]] && _value="$(sed -n 's/^GOOGLE_IOS_CLIENT_ID=//p' "$_env" | tail -1)"
if [[ "$_value" == *.apps.googleusercontent.com ]]; then
  printf '// Generated by scripts/dart-defines.sh from .env; git-ignored.\nGOOGLE_REVERSED_CLIENT_ID=com.googleusercontent.apps.%s\n' \
    "${_value%.apps.googleusercontent.com}" > "$_ios"
fi
# rbacr, which the app asks for the user's own roles, maintenance mode and
# vouchers, with the user's Google ID token: the same rbacr as the auth API
# the build talks to. scripts/deploy.sh exports the stage's RBACR_URL and
# RBACR_SYSTEM; scripts/make.sh, scripts/flutter-run.sh and
# scripts/android-install.sh (whose builds call production's auth API) GA
# rbacr; otherwise, a local web build
# behind the local Floci API, rbacr's RC from .env (RBACR_RC_URL, else
# https://rc.rbacr.nu01.com), as that API. Never .env's RBACR_URL: that one
# is for deploys. Public URLs; the tokens are never passed.
for _name in RBACR_URL RBACR_SYSTEM; do
  _value="${!_name:-}"
  if [[ -z "$_value" && -f "$_env" ]]; then
    _value="$(sed -n "s/^${_name/RBACR_/RBACR_RC_}=//p" "$_env" | tail -1)"
  fi
  [[ "$_name" == RBACR_URL ]] && _value="${_value:-https://rc.rbacr.nu01.com}"
  [[ "$_name" == RBACR_SYSTEM ]] && _value="${_value:-presence}"
  if [[ "$_name" == RBACR_URL && ! "$_value" =~ ^(https://[A-Za-z0-9.-]+(:[0-9]+)?|http://(localhost|127\.0\.0\.1)(:[0-9]+)?)/?$ ]]; then
    echo "error: $_name must be an https origin (or http://localhost), not '$_value'" >&2
    return 1 2>/dev/null || exit 1
  fi
  if [[ "$_name" == RBACR_SYSTEM && ! "$_value" =~ ^[a-z0-9][a-z0-9_.:-]{0,62}$ ]]; then
    echo "error: $_name must be an rbacr system ID, not '$_value'" >&2
    return 1 2>/dev/null || exit 1
  fi
  DART_DEFINES+=(--dart-define="${_name}=${_value}")
done

unset _allowed _env _name _value _ios
